"""
Holds extensive or repetitive help, explaning, descriptive texts.
"""

help = "### Hello! I'm Droneboi map bot. Need some help? Don't worry! Here's a small list of all commands:\n\n - //help - \n -# for more info\n - //new - \n -# exciting news, planned features and more!\n - //ping - \n -# check bot responsiveness\n - //map - \n -# get droneboi claims map. Automatically updated.\n - //map update - \n -# manually update the map\n - //auto map - \n -# Sets a specified channel for auto map updates. More info about it and related commands under '//auto map` \n - //siegeping - \n -# Here you can personalize pings if a siege is about to start. You can set factions to trigger the command, a channel for the command to run and a list of people or role's ids to ping. More info about it in '//siegeping'\n - //faction - \n -# edit and see faction custom colors. '//faction' for more info.\n - //leaderboard - \n -# get leaderboard of factions sorted by who owns more stations.\n - //market - \n -# maps and info related to economy. Where to bug Rift Crystals or sell minerals can be found here. Type '//market' for more info.\n - //crystal - \n -# a shortcut of the '//market get {item}' command. Shows a map of stations that sell crystals.\n - //image - \n -# A really cool tweak by *@KaasKroket*. About Ships and Images. '//image help' for more info\n - //analysis - \n -# Siege board or heatmaps. Analysis of sieges can be found here.\n - //duck - \n -# ?\n - //change-log - \n -# '//change-log' for more info\n - //feedback - \n -# Any ideias? DM, ping me or send it here. It's a way to keep track of what you guys want to be added/changed on the bot."

new="```Version:2.1\nYet another restructuring. If u find any bugs please let me know through '//feedback'!\nJoin our new DBMB dev Discord! [https://discord.gg/VmGHZr4WGE] \n\nAdded /slash compatibility to more commands.\n\n\n • Added an option to generate an image with LEDs. Do //image and check it out! (By @KaasKroket) • Removed //ephemeral and //call help.\n • Changes on source code made the bot faster and easier to maintain.\n • //siege-ping is now //siegeping. The command itself is more simple and straightforward now as well.\n • The bot will now appear as `typing` when doing more time consuming operations\n • Sometimes when typing a command with double slashes, the slash commands pops up, which can be a burden. So the bot acceps `>` as well to those who have problems with `//`.\n\n\nPlanned Features:\nApp commands. Also planning to use embeds and views where i see fit.\n\nKnown issues:slash commands sometimes makes it hard to use double slash commands. Type an extra space or use `>` instead.\nThere's no way to add people to 'faction color whitelist`, I'll be doing it manually for the time being.```"

help_update="## Automatic Claims Map Updates command tree.\n  '`auto map`' for short.\n - //auto map set - \n -# Set's a channel to receive auto updates.\n - - - Use this command on the channel you want to receive auto updates.\n - - - Be aware that the bot needs access to the channel and you need ADMIN permission.\n - //auto map get - \n -# Will return a link to the current configured channel.\n - //auto map test - \n -# This command will ping you in the channel selected for auto updates.\n\n - How to remove a channel that was set for auto updates? Will be implemented soon, fow now, either override it with `//auto map set` or DM me to manual removal."

siege_ping = "## Siegeping Command Tree.\nHave personalized DBC siege pings on discord.\n - //siegeping set\n - - channel\n -# - - - Sets a channel for siege pings on the server. You must be an admin to change that. You must #mention the channel.\n - //siegeping get\n - - channel\n -# - - - Returns the channel set to siege pings.\n - - factions\n -# - - - Returns all faction names that will trigger pings.\n - - ids\n -# - - - Returns all ids, either users or roles, that will get pinged once the command is triggered.\n - //siegeping add\n - - faction\n -# - - - Adds a faction name. It will trigger pings if this faction is getting sieged.\n - - id\n -# - - - Adds an id, either user or role, to get pinged.\n - //siegeping del\n - - faction\n -# - - - Deletes a faction name from the list.\n - - id\n -# - - - Deletes an id from the list.\n - //siegeping test\n -# - - - Test the pings. Will send an example layout and ping you as a test.\n-# Remember that you must be an server admin to change, edit and test the channel, the factions or the ids."

sosCall = "```Bot malfunctioning? Needs help to set siege-pings? Want help understand what certain command dows? But don't want to have to invite someone to the server so they can fix it? That's this command intent. \n\nWith this command you can call the owner to have acces to a certain channel and help you.\nThe owner only have acces to the channel you used the command.\n\n - '//call help' opens a request for me to connect. Be aware i have to accept the request and obviously to be awake at the time.\n - '//call cancel' cancel the request\n - '//call status' returns the status of the request for that channel. To get all channels request status use '//call status all'.\n\n Once the connection is made, simply type 'hang up' to close it.```"

faction_color_help = '## Faction Color Command Tree.\n\n- //faction color set "{Hex code}" - \n -# Edit faction color\n -# - - - Hex code format should be "#rrggbb"\n -# - - - Example: "//faction color set #ffffff"\n- //faction color get - \n -# Returns a list of configured custom faction colors.'