#1.20 jun 7

help = "### Hello! I'm Droneboi map bot. Need some help? Don't worry! Here's a small list of all commands:\n\n - //help - \n -# for more info\n - //new - \n -# exciting news, planned features and more!\n - //ping - \n -# check bot responsiveness\n - //map - \n -# get droneboi claims map. Automatically updated.\n - //map update - \n -# manually update the map\n - //auto map - \n -# Sets a specified channel for auto map updates. More info about it and related commands under '//auto map help` \n - //siege-ping - \n -# Here you can personalize pings if a siege is about to start. You can set factions to trigger the command, a channel for the command to run and a list of people or role's ids to ping. More info about it in '//siege-ping'\n - //faction - \n -# edit and see faction custom colors. '//faction' for more info.\n - //leaderboard - \n -# get leaderboard of factions sorted by who owns more stations.\n - //market - \n -# maps and info related to economy. Where to bug Rift Crystals or sell minerals can be found here. Type '//market' for more info.\n - //crystal - \n -# a shortcut of the '//market get {item}' command. Shows a map of stations that sell crystals.\n - //image - \n -# A really cool tweak by *@KaasKroket*. About Ships and Images. '//image help' for more info\n - //analysis - \n -# Siege board or heatmaps. Analysis of sieges can be found here.\n - //duck - \n -# ?\n - //call help - \n -# Calls the owner to receive support directly through the bot. '//call' for more info {probably will be discontinued due to no use}\n - //ephemeral - \n -# Turns on/off messages only visible to the sender. '//ephemeral' for more info.\n - //change-log - \n -# '//change-log' for more info\n - //feedback - \n -# Any ideias? DM, ping me or send it here. It's a way to keep track of what you guys want to be added/changed on the bot."

new="```Version:2.0\nHuge bot restructuring. If u find any bugs please let me know through '//feedback'!\nJoin our new DBMB dev Discord! [https://discord.gg/VmGHZr4WGE] \n\nThe bot now accepts slash commands! Some commands aren't compatible tho.\n\n\n • Added '//image'. A really cool function by @Kaas_Kroket! Try it out!\n • Added '//analysis'. Analysis of sieges like most attacked star, faction that most failed to siege in the last 100 sieges or siege heatmap. Analysis on sieges can be found here.\n • Added '//ephemeral'. If you want to make messages only visible to the sender use this command. Remember that some commands aren't compatible with ephemeral mode.\n\n\nPlanned Features:\nApp commands.\n\nKnown issues:slash commands sometimes makes it hard to use double slash commands. Typing space after a double slash command usually works.```"

help_update="### Automatic Claims Map Updates command tree.\n'`auto map`' for short.\n```//auto map set - 'set channel for auto updates'. Use this command on the channel you want to receive auto updates. Be aware that the bot needs access to the channel and you need ADMIN permission.\n\n//auto map get - 'get the channel set for auto updates'. Will return a link to the channel\n\n//auto map test - 'test the channel set for auto updates'. This command will ping you in the channel selected for auto updates.\n\n\nHow to remove a channel that was set for auto updates? Ask me, i could make a command for this but honestly i'm lazyness got me...```"

siege_ping = "Siege-ping commands group. Personalize pings for DBC sieges.\n\n- //siege-ping set\n  - channel\n    - Sets an channel for siege pings on the server. You must be an admin to change that. Either you send the channel ID or 'here' which sets the channel the same where the command as used.\n- //siege-ping get\n  - channel\n    - Returns the channel set to siege updates.\n  - factions\n    - Returns all faction name that will trigger pings.\n  - ids\n    - Returns all ids, either user or role, that will get pinged once the command is triggered.\n- //siege-ping add\n  - faction\n    - Adds a faction name. It will trigger pings if this faction is getting sieged.\n  - id\n    - Adds an id, either user or role, to get pinged.\n- //siege-ping del\n  - faction\n    - Deletes a faction name from the triggers list.\n  - id\n    - Deletes an id, either user or role, to not get pinged anymore.\n- //siege-ping test\n  - Test the pings. Will send a ping message for testing.\n\n\n- Remember that you must be an server admin to change, edit and test the channel, the factions or the ids."

sosCall = "```Bot malfunctioning? Needs help to set siege-pings? Want help understand what certain command dows? But don't want to have to invite someone to the server so they can fix it? That's this command intent. \n\nWith this command you can call the owner to have acces to a certain channel and help you.\nThe owner only have acces to the channel you used the command.\n\n - '//call help' opens a request for me to connect. Be aware i have to accept the request and obviously to be awake at the time.\n - '//call cancel' cancel the request\n - '//call status' returns the status of the request for that channel. To get all channels request status use '//call status all'.\n\n Once the connection is made, simply type 'hang up' to close it.```"